### ISSUE TITLE
🚧 Roadmap

### ISSUE THREAD

**Issue by liyasthomas** [hoppscotch/hoppscotch#1166]
**Bugs:**
- [ ] Refactor `queryString <=> UI` implementation
  status: `planned`

**Features:**
- [ ] Refactor state system
  status: `planned`

- [ ] Refactor Firebase transactions
status: `planned`

- [ ] Request as an object (@AndrewBastin) 
  status: `deferred`

**Core:**
- [ ] REST features in GraphQL
  status: `planned`

- [ ] Teams collaboration
  status: `WIP` #879
